### PR TITLE
tests kata-4 (warrior)

### PR DESCRIPTION
**Pull request by Maksym637**
Please, check my work !

### CODE REVIEW

**Comment by lhalam** [comment]
Conflicting files
src/test/java/com/org/ita/kata/EightTest.java
src/test/java/com/org/ita/kata/FiveTest.java
src/test/java/com/org/ita/kata/providers/DataProviderEight.java

**Comment by Maksym637** [comment]
Conflicting files are resolved

**Comment by lhalam** [comment]
Conflicting files
src/test/java/com/org/ita/kata/EightTest.java
src/test/java/com/org/ita/kata/FiveTest.java
src/test/java/com/org/ita/kata/providers/DataProviderEight.java

**Comment by Maksym637** [comment]
Resolved

**Pull request merged**
